Homework_5
mewlunar/AQA_JS pull request #3
Opened 2024-05-30 20:54 UTC by mewlunar

2024-05-30 21:11 UTC, anatoly-karpovich requested changes
Remake task with bytes. And wonderfull job!

2024-05-30 21:11 UTC, anatoly-karpovich commented on Lessen_5_hw/task_1.js
> +for (let j = 0; j < 5; j++) {
U can start from 1, without need to add + 1 in repeat:)

2024-05-30 21:11 UTC, anatoly-karpovich commented on Lessen_5_hw/task_2.js
> +if (bytes < 2 ** 10) {
Nope, need to make a loop to solve the task.

2024-05-31 09:18 UTC, VladimirLQA commented on Lessen_5_hw/task_1.js
> +console.log()
Follow task description - `from 10 to 0`
```suggestion
for (let i = 0; i <= 10; i += 1) {
	console.log(i)
}
```

2024-05-31 09:18 UTC, VladimirLQA commented on Lessen_5_hw/task_2.js
> +for (let i = -h; i <= h; i++) {
Cool solution

2024-05-31 09:18 UTC, VladimirLQA commented on Lessen_5_hw/task_2.js
> +}
```suggestion
for (let i = 1; i <= 100; i++) {
         if (i % 3 === 0 && i % 5 === 0) {
		console.log(i + ' - делится и на 3 на 5')
	} else if (i % 3 === 0) {
		console.log(i + ' - делится на 3')
	} else if (i % 5 === 0) {
		console.log(i + ' - делится на 5')
	} else {
		console.log(i + ' - не делится на 3 или 5')
	}
}
```

2024-05-31 09:18 UTC, VladimirLQA commented on Lessen_5_hw/task_3.js
> +const input = 'AaA'
Try to modify solution to handle such case `Aa 1A` - you need to keep a space and a number in the result string

2024-06-06 19:15 UTC, VladimirLQA requested changes

2024-06-06 19:15 UTC, VladimirLQA commented on Lessen_5_hw/task_2.js
> +		bytes /= 1024
Use `while` for `bytes`

2024-06-06 19:15 UTC, VladimirLQA commented on Lessen_6_hw/task_1.js
> +	}
Return `null` right away after the search
Otherwise you're pushing `undefined` values to result array
```suggestion
	const index = nameArr.indexOf(name);
        if (index === -1) return null;
        return [nameArr[index], salaryArr[index]];
```

2024-06-06 19:15 UTC, VladimirLQA commented on Lessen_6_hw/task_2.js
> +function getEmployeeInfo(pizza) {
Function should be case insensitive

2024-06-06 19:15 UTC, VladimirLQA commented on Lessen_6_hw/task_2.js
> +	}
```suggestion
	return unique.length > 0 ? unique : null;
```

2024-06-06 19:15 UTC, VladimirLQA commented on Lessen_6_hw/task_2.js
> +	for (let i = 1; i < pizza.length; i++) {
Start with `0` index, otherwise you lost first element of an array
```suggestion
	for (let i = 0; i < pizza.length; i++) {
```

2024-06-06 19:15 UTC, VladimirLQA commented on Lessen_6_hw/task_2.js
> +	}
Use just one loop for this task
```suggestion
	for (let i = 0; i < string.length; i++) {
		if (string[i].length > maxLengthWord) {
			maxLengthWord = string[i].length
			arr = [string[i]]
		} else if (string[i].length === maxLengthWord) {
		    arr.push(string[i])
	     }
```

2024-06-06 19:15 UTC, VladimirLQA commented on Lessen_6_hw/task_2.js
> +	return newArr
Try to use `spread` with `new Set` for return value

2024-06-06 19:15 UTC, VladimirLQA commented on Lessen_6_hw/task_2.js
> +	}
Can do it in one line with ternary operator without creating variable, also should be case insensitive

2024-06-06 19:15 UTC, VladimirLQA commented on Lessen_6_hw/task_3.js
> +	num = num.split('')
```suggestion
	num = Math.abs(num).toString().split('')
```

2024-06-06 19:15 UTC, VladimirLQA commented on Lessen_6_hw/task_3.js
> +	}
The solution with ternary operator would be loook even better :)

2024-06-06 19:15 UTC, VladimirLQA commented on Lessen_6_hw/task_3.js
> +function deleteSymbols(string) {
Not important for the task description, but good helper function 👍

2024-06-06 19:15 UTC, VladimirLQA commented on Lessen_6_hw/task_3.js
> +function duplicationCheck(string) {
👍

2024-06-11 17:14 UTC, merged